//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the ds_sensor_msgs package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __ds_sensor_msgs__PHINSCONFIGCONFIG_H__
#define __ds_sensor_msgs__PHINSCONFIGCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace ds_sensor_msgs
{
  class PhinsConfigConfigStatics;

  class PhinsConfigConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(PhinsConfigConfig &config, const PhinsConfigConfig &max, const PhinsConfigConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const PhinsConfigConfig &config1, const PhinsConfigConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, PhinsConfigConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const PhinsConfigConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PhinsConfigConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const PhinsConfigConfig &config) const = 0;
      virtual void getValue(const PhinsConfigConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T PhinsConfigConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T PhinsConfigConfig::* field;

      virtual void clamp(PhinsConfigConfig &config, const PhinsConfigConfig &max, const PhinsConfigConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const PhinsConfigConfig &config1, const PhinsConfigConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, PhinsConfigConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const PhinsConfigConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PhinsConfigConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const PhinsConfigConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const PhinsConfigConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, PhinsConfigConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, PhinsConfigConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<PhinsConfigConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(PhinsConfigConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("zuptMode"==(*_i)->name){zuptMode = boost::any_cast<int>(val);}
        if("altMode"==(*_i)->name){altMode = boost::any_cast<int>(val);}
        if("gps1Rejection"==(*_i)->name){gps1Rejection = boost::any_cast<int>(val);}
        if("gps2Rejection"==(*_i)->name){gps2Rejection = boost::any_cast<int>(val);}
        if("dvl1Rejection"==(*_i)->name){dvl1Rejection = boost::any_cast<int>(val);}
        if("dvl2Rejection"==(*_i)->name){dvl2Rejection = boost::any_cast<int>(val);}
        if("dvlWt1Rejection"==(*_i)->name){dvlWt1Rejection = boost::any_cast<int>(val);}
        if("dvlWt2Rejection"==(*_i)->name){dvlWt2Rejection = boost::any_cast<int>(val);}
        if("depthRejection"==(*_i)->name){depthRejection = boost::any_cast<int>(val);}
        if("usblRejection"==(*_i)->name){usblRejection = boost::any_cast<int>(val);}
      }
    }

    int zuptMode;
int altMode;
int gps1Rejection;
int gps2Rejection;
int dvl1Rejection;
int dvl2Rejection;
int dvlWt1Rejection;
int dvlWt2Rejection;
int depthRejection;
int usblRejection;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int zuptMode;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int altMode;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int gps1Rejection;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int gps2Rejection;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int dvl1Rejection;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int dvl2Rejection;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int dvlWt1Rejection;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int dvlWt2Rejection;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int depthRejection;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int usblRejection;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("PhinsConfigConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const PhinsConfigConfig &__max__ = __getMax__();
      const PhinsConfigConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const PhinsConfigConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const PhinsConfigConfig &__getDefault__();
    static const PhinsConfigConfig &__getMax__();
    static const PhinsConfigConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const PhinsConfigConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void PhinsConfigConfig::ParamDescription<std::string>::clamp(PhinsConfigConfig &config, const PhinsConfigConfig &max, const PhinsConfigConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class PhinsConfigConfigStatics
  {
    friend class PhinsConfigConfig;

    PhinsConfigConfigStatics()
    {
PhinsConfigConfig::GroupDescription<PhinsConfigConfig::DEFAULT, PhinsConfigConfig> Default("Default", "", 0, 0, true, &PhinsConfigConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.zuptMode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.zuptMode = 5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.zuptMode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PhinsConfigConfig::AbstractParamDescriptionConstPtr(new PhinsConfigConfig::ParamDescription<int>("zuptMode", "int", 0, "ZUPT mode", "{'enum': [{'name': 'ZuptNone', 'type': 'int', 'value': 0, 'srcline': 13, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'No Zero Update', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'ZuptStatic10mps', 'type': 'int', 'value': 1, 'srcline': 14, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Static, 10m/s stddev', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'ZuptStatic0p1mps', 'type': 'int', 'value': 2, 'srcline': 15, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Static, 0.1m/s stddev', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'ZuptAutoStatic', 'type': 'int', 'value': 3, 'srcline': 16, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': '0.01m/s stddev when no rotation >10 deg/hr', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'ZuptAutoStaticBench', 'type': 'int', 'value': 4, 'srcline': 17, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': '0.01m/s AND 10 deg/hr stddev when no rotation > 10deg/hr', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'ZuptPosition', 'type': 'int', 'value': 5, 'srcline': 18, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Repeat manual position input every step', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'ZUPT Mode'}", &PhinsConfigConfig::zuptMode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PhinsConfigConfig::AbstractParamDescriptionConstPtr(new PhinsConfigConfig::ParamDescription<int>("zuptMode", "int", 0, "ZUPT mode", "{'enum': [{'name': 'ZuptNone', 'type': 'int', 'value': 0, 'srcline': 13, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'No Zero Update', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'ZuptStatic10mps', 'type': 'int', 'value': 1, 'srcline': 14, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Static, 10m/s stddev', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'ZuptStatic0p1mps', 'type': 'int', 'value': 2, 'srcline': 15, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Static, 0.1m/s stddev', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'ZuptAutoStatic', 'type': 'int', 'value': 3, 'srcline': 16, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': '0.01m/s stddev when no rotation >10 deg/hr', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'ZuptAutoStaticBench', 'type': 'int', 'value': 4, 'srcline': 17, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': '0.01m/s AND 10 deg/hr stddev when no rotation > 10deg/hr', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'ZuptPosition', 'type': 'int', 'value': 5, 'srcline': 18, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Repeat manual position input every step', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'ZUPT Mode'}", &PhinsConfigConfig::zuptMode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.altMode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.altMode = 3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.altMode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PhinsConfigConfig::AbstractParamDescriptionConstPtr(new PhinsConfigConfig::ParamDescription<int>("altMode", "int", 0, "Altitude mode", "{'enum': [{'name': 'AltitudeNone', 'type': 'int', 'value': 0, 'srcline': 21, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Use inertial altitude', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'AltitudeGPS', 'type': 'int', 'value': 1, 'srcline': 22, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Use GPS Height', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'AltitudeDepth', 'type': 'int', 'value': 2, 'srcline': 23, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Use Depth sensor', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'AltitudeHydro', 'type': 'int', 'value': 3, 'srcline': 24, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Hydrography-specific GPS', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Altitude stabilization mode enum'}", &PhinsConfigConfig::altMode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PhinsConfigConfig::AbstractParamDescriptionConstPtr(new PhinsConfigConfig::ParamDescription<int>("altMode", "int", 0, "Altitude mode", "{'enum': [{'name': 'AltitudeNone', 'type': 'int', 'value': 0, 'srcline': 21, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Use inertial altitude', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'AltitudeGPS', 'type': 'int', 'value': 1, 'srcline': 22, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Use GPS Height', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'AltitudeDepth', 'type': 'int', 'value': 2, 'srcline': 23, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Use Depth sensor', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'AltitudeHydro', 'type': 'int', 'value': 3, 'srcline': 24, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Hydrography-specific GPS', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Altitude stabilization mode enum'}", &PhinsConfigConfig::altMode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.gps1Rejection = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.gps1Rejection = 3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.gps1Rejection = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PhinsConfigConfig::AbstractParamDescriptionConstPtr(new PhinsConfigConfig::ParamDescription<int>("gps1Rejection", "int", 0, "GPS 1 rejection filter mode", "{'enum': [{'name': 'FilterForced', 'type': 'int', 'value': 0, 'srcline': 27, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Bypass the outlier rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterOff', 'type': 'int', 'value': 1, 'srcline': 28, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Disable sensor', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterNormal', 'type': 'int', 'value': 2, 'srcline': 29, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Use normal rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterForcedOnce', 'type': 'int', 'value': 3, 'srcline': 30, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Force next measurement, then ignore', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Rejection filter enum'}", &PhinsConfigConfig::gps1Rejection)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PhinsConfigConfig::AbstractParamDescriptionConstPtr(new PhinsConfigConfig::ParamDescription<int>("gps1Rejection", "int", 0, "GPS 1 rejection filter mode", "{'enum': [{'name': 'FilterForced', 'type': 'int', 'value': 0, 'srcline': 27, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Bypass the outlier rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterOff', 'type': 'int', 'value': 1, 'srcline': 28, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Disable sensor', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterNormal', 'type': 'int', 'value': 2, 'srcline': 29, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Use normal rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterForcedOnce', 'type': 'int', 'value': 3, 'srcline': 30, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Force next measurement, then ignore', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Rejection filter enum'}", &PhinsConfigConfig::gps1Rejection)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.gps2Rejection = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.gps2Rejection = 3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.gps2Rejection = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PhinsConfigConfig::AbstractParamDescriptionConstPtr(new PhinsConfigConfig::ParamDescription<int>("gps2Rejection", "int", 0, "GPS 2 rejection filter mode", "{'enum': [{'name': 'FilterForced', 'type': 'int', 'value': 0, 'srcline': 27, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Bypass the outlier rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterOff', 'type': 'int', 'value': 1, 'srcline': 28, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Disable sensor', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterNormal', 'type': 'int', 'value': 2, 'srcline': 29, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Use normal rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterForcedOnce', 'type': 'int', 'value': 3, 'srcline': 30, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Force next measurement, then ignore', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Rejection filter enum'}", &PhinsConfigConfig::gps2Rejection)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PhinsConfigConfig::AbstractParamDescriptionConstPtr(new PhinsConfigConfig::ParamDescription<int>("gps2Rejection", "int", 0, "GPS 2 rejection filter mode", "{'enum': [{'name': 'FilterForced', 'type': 'int', 'value': 0, 'srcline': 27, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Bypass the outlier rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterOff', 'type': 'int', 'value': 1, 'srcline': 28, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Disable sensor', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterNormal', 'type': 'int', 'value': 2, 'srcline': 29, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Use normal rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterForcedOnce', 'type': 'int', 'value': 3, 'srcline': 30, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Force next measurement, then ignore', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Rejection filter enum'}", &PhinsConfigConfig::gps2Rejection)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.dvl1Rejection = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.dvl1Rejection = 3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.dvl1Rejection = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PhinsConfigConfig::AbstractParamDescriptionConstPtr(new PhinsConfigConfig::ParamDescription<int>("dvl1Rejection", "int", 0, "DVL 1 bottom-track rejection filter mode", "{'enum': [{'name': 'FilterForced', 'type': 'int', 'value': 0, 'srcline': 27, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Bypass the outlier rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterOff', 'type': 'int', 'value': 1, 'srcline': 28, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Disable sensor', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterNormal', 'type': 'int', 'value': 2, 'srcline': 29, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Use normal rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterForcedOnce', 'type': 'int', 'value': 3, 'srcline': 30, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Force next measurement, then ignore', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Rejection filter enum'}", &PhinsConfigConfig::dvl1Rejection)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PhinsConfigConfig::AbstractParamDescriptionConstPtr(new PhinsConfigConfig::ParamDescription<int>("dvl1Rejection", "int", 0, "DVL 1 bottom-track rejection filter mode", "{'enum': [{'name': 'FilterForced', 'type': 'int', 'value': 0, 'srcline': 27, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Bypass the outlier rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterOff', 'type': 'int', 'value': 1, 'srcline': 28, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Disable sensor', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterNormal', 'type': 'int', 'value': 2, 'srcline': 29, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Use normal rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterForcedOnce', 'type': 'int', 'value': 3, 'srcline': 30, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Force next measurement, then ignore', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Rejection filter enum'}", &PhinsConfigConfig::dvl1Rejection)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.dvl2Rejection = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.dvl2Rejection = 3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.dvl2Rejection = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PhinsConfigConfig::AbstractParamDescriptionConstPtr(new PhinsConfigConfig::ParamDescription<int>("dvl2Rejection", "int", 0, "DVL 2 bottom-track rejection filter mode", "{'enum': [{'name': 'FilterForced', 'type': 'int', 'value': 0, 'srcline': 27, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Bypass the outlier rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterOff', 'type': 'int', 'value': 1, 'srcline': 28, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Disable sensor', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterNormal', 'type': 'int', 'value': 2, 'srcline': 29, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Use normal rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterForcedOnce', 'type': 'int', 'value': 3, 'srcline': 30, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Force next measurement, then ignore', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Rejection filter enum'}", &PhinsConfigConfig::dvl2Rejection)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PhinsConfigConfig::AbstractParamDescriptionConstPtr(new PhinsConfigConfig::ParamDescription<int>("dvl2Rejection", "int", 0, "DVL 2 bottom-track rejection filter mode", "{'enum': [{'name': 'FilterForced', 'type': 'int', 'value': 0, 'srcline': 27, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Bypass the outlier rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterOff', 'type': 'int', 'value': 1, 'srcline': 28, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Disable sensor', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterNormal', 'type': 'int', 'value': 2, 'srcline': 29, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Use normal rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterForcedOnce', 'type': 'int', 'value': 3, 'srcline': 30, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Force next measurement, then ignore', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Rejection filter enum'}", &PhinsConfigConfig::dvl2Rejection)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.dvlWt1Rejection = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.dvlWt1Rejection = 3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.dvlWt1Rejection = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PhinsConfigConfig::AbstractParamDescriptionConstPtr(new PhinsConfigConfig::ParamDescription<int>("dvlWt1Rejection", "int", 0, "DVL 1 water-track rejection filter mode", "{'enum': [{'name': 'FilterForced', 'type': 'int', 'value': 0, 'srcline': 27, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Bypass the outlier rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterOff', 'type': 'int', 'value': 1, 'srcline': 28, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Disable sensor', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterNormal', 'type': 'int', 'value': 2, 'srcline': 29, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Use normal rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterForcedOnce', 'type': 'int', 'value': 3, 'srcline': 30, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Force next measurement, then ignore', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Rejection filter enum'}", &PhinsConfigConfig::dvlWt1Rejection)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PhinsConfigConfig::AbstractParamDescriptionConstPtr(new PhinsConfigConfig::ParamDescription<int>("dvlWt1Rejection", "int", 0, "DVL 1 water-track rejection filter mode", "{'enum': [{'name': 'FilterForced', 'type': 'int', 'value': 0, 'srcline': 27, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Bypass the outlier rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterOff', 'type': 'int', 'value': 1, 'srcline': 28, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Disable sensor', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterNormal', 'type': 'int', 'value': 2, 'srcline': 29, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Use normal rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterForcedOnce', 'type': 'int', 'value': 3, 'srcline': 30, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Force next measurement, then ignore', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Rejection filter enum'}", &PhinsConfigConfig::dvlWt1Rejection)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.dvlWt2Rejection = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.dvlWt2Rejection = 3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.dvlWt2Rejection = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PhinsConfigConfig::AbstractParamDescriptionConstPtr(new PhinsConfigConfig::ParamDescription<int>("dvlWt2Rejection", "int", 0, "DVL 2 water-track rejection filter mode", "{'enum': [{'name': 'FilterForced', 'type': 'int', 'value': 0, 'srcline': 27, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Bypass the outlier rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterOff', 'type': 'int', 'value': 1, 'srcline': 28, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Disable sensor', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterNormal', 'type': 'int', 'value': 2, 'srcline': 29, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Use normal rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterForcedOnce', 'type': 'int', 'value': 3, 'srcline': 30, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Force next measurement, then ignore', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Rejection filter enum'}", &PhinsConfigConfig::dvlWt2Rejection)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PhinsConfigConfig::AbstractParamDescriptionConstPtr(new PhinsConfigConfig::ParamDescription<int>("dvlWt2Rejection", "int", 0, "DVL 2 water-track rejection filter mode", "{'enum': [{'name': 'FilterForced', 'type': 'int', 'value': 0, 'srcline': 27, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Bypass the outlier rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterOff', 'type': 'int', 'value': 1, 'srcline': 28, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Disable sensor', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterNormal', 'type': 'int', 'value': 2, 'srcline': 29, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Use normal rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterForcedOnce', 'type': 'int', 'value': 3, 'srcline': 30, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Force next measurement, then ignore', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Rejection filter enum'}", &PhinsConfigConfig::dvlWt2Rejection)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.depthRejection = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.depthRejection = 3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.depthRejection = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PhinsConfigConfig::AbstractParamDescriptionConstPtr(new PhinsConfigConfig::ParamDescription<int>("depthRejection", "int", 0, "Depth sensor rejeciton filter mode", "{'enum': [{'name': 'FilterForced', 'type': 'int', 'value': 0, 'srcline': 27, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Bypass the outlier rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterOff', 'type': 'int', 'value': 1, 'srcline': 28, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Disable sensor', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterNormal', 'type': 'int', 'value': 2, 'srcline': 29, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Use normal rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterForcedOnce', 'type': 'int', 'value': 3, 'srcline': 30, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Force next measurement, then ignore', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Rejection filter enum'}", &PhinsConfigConfig::depthRejection)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PhinsConfigConfig::AbstractParamDescriptionConstPtr(new PhinsConfigConfig::ParamDescription<int>("depthRejection", "int", 0, "Depth sensor rejeciton filter mode", "{'enum': [{'name': 'FilterForced', 'type': 'int', 'value': 0, 'srcline': 27, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Bypass the outlier rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterOff', 'type': 'int', 'value': 1, 'srcline': 28, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Disable sensor', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterNormal', 'type': 'int', 'value': 2, 'srcline': 29, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Use normal rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterForcedOnce', 'type': 'int', 'value': 3, 'srcline': 30, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Force next measurement, then ignore', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Rejection filter enum'}", &PhinsConfigConfig::depthRejection)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.usblRejection = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.usblRejection = 3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.usblRejection = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PhinsConfigConfig::AbstractParamDescriptionConstPtr(new PhinsConfigConfig::ParamDescription<int>("usblRejection", "int", 0, "USBL rejection filter mode", "{'enum': [{'name': 'FilterForced', 'type': 'int', 'value': 0, 'srcline': 27, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Bypass the outlier rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterOff', 'type': 'int', 'value': 1, 'srcline': 28, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Disable sensor', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterNormal', 'type': 'int', 'value': 2, 'srcline': 29, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Use normal rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterForcedOnce', 'type': 'int', 'value': 3, 'srcline': 30, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Force next measurement, then ignore', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Rejection filter enum'}", &PhinsConfigConfig::usblRejection)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PhinsConfigConfig::AbstractParamDescriptionConstPtr(new PhinsConfigConfig::ParamDescription<int>("usblRejection", "int", 0, "USBL rejection filter mode", "{'enum': [{'name': 'FilterForced', 'type': 'int', 'value': 0, 'srcline': 27, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Bypass the outlier rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterOff', 'type': 'int', 'value': 1, 'srcline': 28, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Disable sensor', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterNormal', 'type': 'int', 'value': 2, 'srcline': 29, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Use normal rejection filter', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'FilterForcedOnce', 'type': 'int', 'value': 3, 'srcline': 30, 'srcfile': '/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg', 'description': 'Force next measurement, then ignore', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Rejection filter enum'}", &PhinsConfigConfig::usblRejection)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(PhinsConfigConfig::AbstractGroupDescriptionConstPtr(new PhinsConfigConfig::GroupDescription<PhinsConfigConfig::DEFAULT, PhinsConfigConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<PhinsConfigConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<PhinsConfigConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<PhinsConfigConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    PhinsConfigConfig __max__;
    PhinsConfigConfig __min__;
    PhinsConfigConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const PhinsConfigConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static PhinsConfigConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &PhinsConfigConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const PhinsConfigConfig &PhinsConfigConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const PhinsConfigConfig &PhinsConfigConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const PhinsConfigConfig &PhinsConfigConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<PhinsConfigConfig::AbstractParamDescriptionConstPtr> &PhinsConfigConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<PhinsConfigConfig::AbstractGroupDescriptionConstPtr> &PhinsConfigConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const PhinsConfigConfigStatics *PhinsConfigConfig::__get_statics__()
  {
    const static PhinsConfigConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = PhinsConfigConfigStatics::get_instance();

    return statics;
  }

//#line 13 "/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg"
      const int PhinsConfig_ZuptNone = 0;
//#line 14 "/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg"
      const int PhinsConfig_ZuptStatic10mps = 1;
//#line 15 "/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg"
      const int PhinsConfig_ZuptStatic0p1mps = 2;
//#line 16 "/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg"
      const int PhinsConfig_ZuptAutoStatic = 3;
//#line 17 "/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg"
      const int PhinsConfig_ZuptAutoStaticBench = 4;
//#line 18 "/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg"
      const int PhinsConfig_ZuptPosition = 5;
//#line 21 "/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg"
      const int PhinsConfig_AltitudeNone = 0;
//#line 22 "/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg"
      const int PhinsConfig_AltitudeGPS = 1;
//#line 23 "/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg"
      const int PhinsConfig_AltitudeDepth = 2;
//#line 24 "/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg"
      const int PhinsConfig_AltitudeHydro = 3;
//#line 27 "/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg"
      const int PhinsConfig_FilterForced = 0;
//#line 28 "/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg"
      const int PhinsConfig_FilterOff = 1;
//#line 29 "/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg"
      const int PhinsConfig_FilterNormal = 2;
//#line 30 "/home/einar/Desktop/Robotics_projects/Masters-project/catkin_ws/src/ds_msgs/ds_sensor_msgs/cfg/PhinsConfig.cfg"
      const int PhinsConfig_FilterForcedOnce = 3;
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __PHINSCONFIGRECONFIGURATOR_H__
